### ISSUE TITLE
CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by slyapustin** [pielgrzym/django-imaging#3]
When i try to remove image in sample app i get 403 error.
Django needed CSRF token for AJAX  POST requests.
https://docs.djangoproject.com/en/dev/ref/contrib/csrf/#ajax

**Comment by pielgrzym** [comment]
Thanks for pointing that out :)

2012/11/19 inoks notifications@github.com

> When i try to remove image in sample app i get 403 error.
> Django needed CSRF token for AJAX POST requests.
> https://docs.djangoproject.com/en/dev/ref/contrib/csrf/#ajax
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pielgrzym/django-imaging/issues/3.

## 

Pozdrawiam, JN
